### ISSUE TITLE
Board complete, uploaded code but not getting serial

### ISSUE THREAD

**Issue by mjschipper** [mhgolkar/Melon_Green#2]
Hello. I have built one of your custom boards and was able to upload the code via avrdude and usbasp however i cant seem to be getting a serial terminal running. Also im not getting any LED's turning on. There is voltage on the 7805 and 5v to the VCC sensor/ RTC pins. Also all the pins on the Atmega are connected correctly. Any ideas what i can test? It's strange because the power LED shouldnt rely on the Atmega at all. I'm running 12vdc input.

**Comment by mjschipper** [comment]
I had the code working on an UNO but the serial was really glitchy and i couldnt get past the main menu.

**Comment by mhgolkar** [comment]
+ Are you using the serial terminal of Arduino IDE ? I remember it not supporting some of the control characters used in the serial communication. Have you tried another option like putty?
+ I suggest double checking the speed (baud rate) for the serial communication as well. Make sure it's the same value in both the board/code's configuration and the terminal you're using.
+ Regarding the custom board I would look for the problem in the pin configurations.
